### ISSUE TITLE
Expired creation requests nodes are not terminated

### ISSUE THREAD

**Issue by nidhi0622** [Azure/cyclecloud-symphony#51]
An assertion error to avoid duplicate writes lead to zombie nodes not being terminated. Below error seen in logs:2024-05-19 14:14:59,310 - cyclecloud - ERROR - Could not terminate expired requests
Traceback (most recent call last):
  File "/var/tmp/symphony/hostfactory/conf/providers/azurecc/scripts/src/util.py", line 213, in _wrap
    return func(*args, **kwargs)
  File "/var/tmp/symphony/hostfactory/conf/providers/azurecc/scripts/src/cyclecloud_provider.py", line 854, in _create_status
    return output_handler.handle(response)
  File "/var/tmp/symphony/hostfactory/conf/providers/azurecc/scripts/src/cyclecloud_provider.py", line 1298, in handle
    assert not self.written
AssertionError

**Comment by nidhi0622** [comment]
Fixed in 1.0.12
